input_file = "/groups/funke/funkelab/malinmayorc/linajea/linajea_experiments/data/140521/140521.zarr"
output_file = "/groups/funke/funkelab/malinmayorc/linajea/linajea_experiments/data/140521/140521.zarr"
times = [0, 1]
dataset = 'raw'
sigma = [1, 2, 2]
min_percentile = 1
downsample = 100
min_mean_distance = 0.4
singularity_image = "linajea/linajea:v1.2-dev"
