[general]
# error   40
# warning 30
# info    20
# debug   10
logging = 20
db_host = "mongodb://linajeaAdmin:FeOOHnH2O@funke-mongodb4/admin?replicaSet=rsLinajea"
seed = 42
setup_dir = "/groups/funke/home/hirschp/linajea_experiments/unet_setups/celegans_setups/ctc_100"
sparse = false

[model]
train_input_shape = [ 7, 40, 148, 148,]
predict_input_shape = [ 7, 80, 260, 260,]
fmap_inc_factors = 3
downsample_factors = [ [ 1, 2, 2,], [ 1, 2, 2,], [ 2, 2, 2,],]
kernel_size_down = [[3, 3], [3, 3], [3, 3], [3, 3]]
kernel_size_up = [[3, 3], [3, 3], [3, 3]]
# kernel_size_down = [[[1, 1, 3, 3], [1, 1, 3, 3]],
#                     [[1, 1, 3, 3], [1, 1, 3, 3]],
#                     [[3, 3, 3, 3], [3, 3, 3, 3]],
#                     [[3, 3, 3, 3], [3, 3, 3]]]
# kernel_size_up = [[[1, 3, 3], [1, 3, 3]],
#                   [[1, 3, 3], [1, 3, 3]],
#                   [[3, 3, 3], [3, 3, 3]]]
constant_upsample = false
average_vectors = false
nms_window_shape = [ 3, 11, 11,]
unet_style = "multihead"
num_fmaps = 36
cell_indicator_weighted = true
path_to_script = "/groups/funke/home/hirschp/linajea_experiments/unet_setups/celegans_setups/mknet_celegans.py"

[train]
path_to_script = "/groups/funke/home/hirschp/linajea_experiments/unet_setups/celegans_setups/train_val_celegans.py"
val_log_step = 10
# radius for binary map -> *2
parent_radius = [0.1, 16.0, 8.0, 8.0]
# parent_radius = [0.1, 28.0, 8.0, 8.0]
# sigma for Gauss -> ~*4 (5 in z -> in 3 slices)
# rasterize_radius = [0.1, 5.0, 3.0, 3.0]
rasterize_radius = [0.1, 16.0, 5.0, 5.0]
cache_size = 10
checkpoint_stride = 10000
snapshot_stride = 1000
profiling_stride = 100
max_iterations = 400000
# parent_vectors_loss_transition = 50000
# TODO cell_density = true
cell_density = 22

[train.job]
num_workers = 5
queue = "gpu_rtx"

[train.use_radius]
15 = 30
60 = 20
100 = 15
1000 = 10

[train.augment]
divisions = true
reject_empty_prob = 0.99
# TODO dense_gt = true
# default/None, minmax, mean, median
# normalization = 'percminmax'
# perc_min = 'perc0_01'
# perc_max = 'perc99_99'
# norm_bounds = [100, 5000]
# norm_min = 100
# norm_max = 5000
# norm_min = 2000
# norm_max = 7500

[optimizerTF1]
# optimizer = "GradientDescentOptimizer"
# optimizer = "MomentumOptimizer"
optimizer = "AdamOptimizer"
[optimizerTF1.args]
learning_rate = 0.00005
# momentum = 0.9
[optimizerTF1.kwargs]
beta1 = 0.95
beta2 = 0.999
epsilon = 1e-8

[extract]
block_size = [ 5, 512, 512, 712,]
use_pv_distance = true
[extract.edge_move_threshold]
50 = 65
100 = 50
1000 = 35

[extract.job]
num_workers = 32
queue = "local"


[solve]
from_scratch = true
non_minimal = false
# write_struct_svm = "ssvm_ckpt_400000_2"
check_node_close_to_roi = false
# add_node_density_constraints = true
[solve.add_node_density_constraints]
30 = 35
60 = 25
100 = 15
1000 = 10
[solve.job]
num_workers = 14
queue = "local"


# [[solve.parameters]]
# # w class id 
# weight_node_score =  -32.975124422814076   
# selection_constant = 19.93021599203037   
# track_cost =         14.2873207051496    
# # disappear cost     -0.0                
# weight_division =    -32.352812734926246 
# division_constant =  4.328601899023063   
# weight_child =       12.341243097747999  
# weight_continuation =1.000026428524669   
# weight_edge_score =  0.3857184722378113


# cell_cycle_key = '210105_144601/test/40000_'
# block_size = [15, 512, 512, 712]
# context = [2, 100, 100, 100]


[solve.parameters_search]
weight_node_score =   [-13, -17, -21]
selection_constant =  [6, 9, 12]
track_cost =          [7, 11, 15]
weight_division =     [-8, -11]
division_constant =   [6.0, 2.5]
weight_child =        [1.0, 2.0]
weight_continuation = [-1.0]
weight_edge_score =   [0.35]

# cell_cycle_key = ['210105_144601/test/40000_']

block_size = [[15, 512, 512, 712]]
context = [[2, 100, 100, 100]]
num_random_configs = 100
random_search = false


[predict]
path_to_script = "/groups/funke/home/hirschp/linajea_experiments/unet_setups/celegans_setups/predict_celegans.py"
path_to_script_db_from_zarr = "/groups/funke/home/hirschp/linajea_experiments/unet_setups/celegans_setups/write_cells_celegans.py"
output_zarr_prefix = "/nrs/funke/hirschp/linajea_experiments"
write_to_zarr = true
write_to_db = true
write_db_from_zarr = false
processes_per_worker = 5
[predict.job]
num_workers = 4
queue = "gpu_tesla"

[train_data]
voxel_size = [ 1, 5, 1, 1,]
[train_data.roi]
offset = [ 0, 0, 0, 0,]
shape = [ 200, 175, 512, 712,]
[[train_data.data_sources]]
gt_db_name = "linajea_celegans_ctc1_z5"

[train_data.data_sources.datafile]
filename = "/nrs/funke/hirschp/Fluo-N3DH-CE/Fluo-N3DH-CE_01"
group = "volumes/raw_nested"
[[train_data.data_sources]]
gt_db_name = "linajea_celegans_ctc2_z5"

[train_data.data_sources.datafile]
filename = "/nrs/funke/hirschp/Fluo-N3DH-CE/Fluo-N3DH-CE_02"
group = "volumes/raw_nested"

[test_data]
checkpoint = 400000
cell_score_threshold = 0.2
voxel_size = [ 1, 5, 1, 1,]
[test_data.roi]
offset = [ 0, 0, 0, 0,]
shape = [ 200, 175, 512, 712,]
[[test_data.data_sources]]
gt_db_name = "linajea_celegans_ctc2_z5"

[test_data.data_sources.datafile]
filename = "/nrs/funke/hirschp/Fluo-N3DH-CE/Fluo-N3DH-CE_02"
group = "volumes/raw_nested"

[validate_data]
checkpoints = [ 400000,]
cell_score_threshold = 0.2
voxel_size = [ 1, 5, 1, 1,]
[validate_data.roi]
offset = [ 0, 0, 0, 0,]
shape = [ 200, 175, 512, 712,]
[[validate_data.data_sources]]
gt_db_name = "linajea_celegans_ctc2_z5"

[validate_data.data_sources.datafile]
filename = "/nrs/funke/hirschp/Fluo-N3DH-CE/Fluo-N3DH-CE_02"
group = "volumes/raw_nested"


[evaluate]
from_scratch = true
[evaluate.parameters]
matching_threshold = 15
sparse = false
[evaluate.job]
num_workers = 1
queue = "local"
[evaluate.parameters.roi]
offset = [0, 0, 0, 0]
shape = [200, 155, 512, 712]

[train.augment.elastic]
control_point_spacing = [ 5, 25, 25,]
jitter_sigma = [ 1, 1, 1,]
rotation_min = -10
rotation_max = 10
subsample = 4
use_fast_points_transform = false

[train.augment.shift]
prob_slip = 0.1
prob_shift = 0.1
sigma = [ 0, 4, 4, 4,]

[train.augment.intensity]
scale = [ 0.8, 1.2,]
shift = [ -0.1, 0.1,]
# [train.augment.intensity]
# scale = [0.9, 1.1]
# shift = [-0.001, 0.001]


[train.augment.noise_gaussian]
var = [ 0.3,]

[train.augment.noise_saltpepper]
amount = [ 0.001,]
