[general]
logging = 20
db_host = "mongodb://linajeaAdmin:FeOOHnH2O@funke-mongodb4/admin?replicaSet=rsLinajea"
setup_dir = "/groups/funke/home/hirschp/linajea_experiments/classifier_setups/setup_class_3XX/experiments/classifier_ls_40_swa_emb1_rep10_c"
seed = 42

[model]
net_name = "class_net"
#input_shape = [ 5, 64, 64, 64,]
# input_shape = [ 5, 48, 48, 48,]
input_shape = [5, 32, 32, 32,]
pad_raw = [ 3, 30, 30, 30,]
network_type = "resnet"
# network_type = "efficientnet"   #
num_fmaps = [ 16, 32, 64, 96,]
resnet_size = "18"
num_blocks = [ 3, 4, 4,]
use_bottleneck = true
# efficientnet_size = "B7"
activation = "relu"
padding = "same"
use_batchnorm = true
use_bias = true
num_classes = 3
use_conv4d = true
path_to_script = "/groups/funke/home/hirschp/linajea_experiments/classifier_setups/setup_class_3XX/mknet.py"
merge_time_voxel_size = 2
use_dropout = false
use_global_pool = true
make_isotropic = false
classes = [ "daughter", "mother", "normal",]
class_ids = [ 2, 1, 0,]
with_polar = true
#regularizer_weight = 0.00001
focal_loss = false

[train]
use_tf_data = false
val_log_step = 10
path_to_script = "/groups/funke/home/hirschp/linajea_experiments/classifier_setups/setup_class_3XX/train.py"
use_auto_mixed_precision = true
batch_size = 16
cache_size = 128
max_iterations = 60000
checkpoint_stride = 5000
snapshot_stride = 500
profiling_stride = 1000
use_swa = true
swa_start_it = 4999
swa_freq_it = 1000
# [optimizerTF2]
# optimizer = "SGD"

[evaluate]
max_samples = 200000
metric = "AP"
one_off = false
prob_threshold = 0.75
dry_run = false
find_fn = false

[predict]
batch_size = 64
path_to_script = "/groups/funke/home/hirschp/linajea_experiments/classifier_setups/setup_class_3XX/predict.py"
test_time_reps = 1
use_swa = false

[train_data]
use_database = false
[[train_data.data_sources]]

[train_data.data_sources.datafile]
filename = "/nrs/funke/hirschp/mskcc_lightsheet/mskcc_lightsheet_emb1"
group = "volumes/raw_nested"

[[train_data.data_sources]]

[train_data.data_sources.datafile]
filename = "/nrs/funke/hirschp/mskcc_lightsheet/mskcc_lightsheet_emb1/polar"
group = "volumes/raw_nested"


[test_data]
use_database = true
skip_predict = false
checkpoint = 60000
prob_threshold = 0.1
[[test_data.data_sources]]

[test_data.data_sources.datafile]
filename = "/nrs/funke/hirschp/mskcc_lightsheet/mskcc_lightsheet_emb3"
group = "volumes/raw_nested"

[[test_data.data_sources]]

[test_data.data_sources.datafile]
filename = "/nrs/funke/hirschp/mskcc_lightsheet/mskcc_lightsheet_emb3/polar"
group = "volumes/raw_nested"


[validate_data]
use_database = false
# prob_thresholds = [ 0.1, 0.5, 0.75, 0.9, 0.99,]
prob_thresholds = [ 0.1,]
checkpoints = [40000, 50000, 60000]
skip_predict = false
[[validate_data.data_sources]]

[validate_data.data_sources.datafile]
filename = "/nrs/funke/hirschp/mskcc_lightsheet/mskcc_lightsheet_emb2"
group = "volumes/raw_nested"

[[validate_data.data_sources]]

[validate_data.data_sources.datafile]
filename = "/nrs/funke/hirschp/mskcc_lightsheet/mskcc_lightsheet_emb2/polar"
group = "volumes/raw_nested"

[train.job]
num_workers = 4
queue = "gpu_tesla"

[train.augment]
# min_key = "perc0_01"
# max_key = "perc99_99"
min_key = "min"
max_key = "max"
# norm_min = 2000
# norm_max = 7500


# [optimizerTF2.kwargs]
# learning_rate = 0.0001
# # beta_1 = 0.95
# # beta_2 = 0.999
# # epsilon = 1e-8

[optimizerTF1]
# optimizer = "AdamWOptimizer"
lr_schedule = "1_decay_step"
optimizer = "AdamOptimizer"
[optimizerTF1.args]
# weight_decay = 1e-4
learning_rate = 0.0005

[optimizerTF1.kwargs]
# learning_rate = 0.0005
beta1 = 0.95
beta2 = 0.999
epsilon = 1e-8

# [optimizerTF1]
# optimizer = "MomentumOptimizer"
# [optimizerTF1.args]
# learning_rate = 0.0001
# momentum = 0.9

# [optimizerTF1.kwargs]


[predict.job]
num_workers = 4
queue = "gpu_rtx"

[train_data.roi]
offset = [ 0, 0, 0, 0,]
# shape = [ 200, 500, 500, 500,]
shape = [ 270, 500, 500, 500,]

[test_data.roi]
offset = [ 0, 0, 0, 0,]
# shape = [ 200, 500, 500, 500,]
shape = [ 270, 500, 500, 500,]

[test_data.db_meta_info]
setup_dir = "ls_38_emb1_mdc_3"
checkpoint = 400000
cell_score_threshold = 0.2

[validate_data.roi]
offset = [ 0, 0, 0, 0,]
# shape = [ 200, 500, 500, 500,]
shape = [ 270, 500, 500, 500,]

[validate_data.db_meta_info]
setup_dir = "ls_38_emb1_mdc_3"
checkpoint = 400000
cell_score_threshold = 0.2

[train.augment.elastic]
control_point_spacing = [ 10, 10, 10,]
jitter_sigma = [ 1, 1, 1,]
rotation_min = -45
rotation_max = 45
rotation_3d = true
subsample = 4

# [train.augment.intensity]
# scale = [ 0.99, 1.01,]
# shift = [ -0.001, 0.001,]

[train.augment.intensity]
scale = [ 0.9, 1.1,]
shift = [ -0.01, 0.01,]

[train.augment.simple]
mirror = [ 1, 2, 3,]
transpose = [ 1, 2, 3,]

[train.augment.jitter]
jitter = [ 0, 3, 3, 3,]

# [train.augment.noise_gaussian]
# var = [ 0.3,]

# [train.augment.noise_saltpepper]
# amount = [ 0.0001,]

# [train.augment.noise_speckle]
# var = [ 0.05,]

# [train.augment.histogram]
# range_low = 0.1
# range_high = 1.0
# after_int_aug = false

[evaluate.parameters.matching_threshold]
50 = 21
1000 = 15

[evaluate.parameters.roi]
offset = [ 0, 0, 0, 0,]
# shape = [ 200, 500, 500, 500,]
shape = [ 270, 500, 500, 500,]
