[general]
setup = "setup11_simple_train_middle"
iteration = 400000
sample = "140521"
frames = [ 400, 450,]
db_host = "localhost"
db_name = "linajea_140521_setup11_simple_late_1_400000"
data_dir = "../data"
setups_dir = "../unet_setups"
data_file = "140521.n5"

[predict]
cell_score_threshold = 0.4
num_workers = 20
processes_per_worker = 10

[extract_edges]
edge_move_threshold = 40
block_size = [ 5, 500, 500, 500,]
num_workers = 32
use_pv_distance = true

[solve]
block_size = [ 5, 500, 500, 500,]
context = [ 2, 100, 100, 100,]
num_workers = 8
from_scratch = false
max_cell_move = 40
track_cost = 0.625
selection_constant = -0.2
weight_node_score = -0.03
weight_edge_score = 0.02
version = 'v1.3-dev'

[evaluate]
matching_threshold = 20
gt_db_name = "linajea_140521_gt_late"
sparse = true
from_scratch = true
validation_score = false
