[general]
setup = "setup111_simple_train_side_2"
iteration = 400000
sample = "160328"
db_host = "mongodb://linajeaAdmin:FeOOHnH2O@funke-mongodb4/admin?replicaSet=rsLinajea"
db_name = "linajea_160328_setup111_simple_eval_side_1_400000_te"
prediction_type = "cell_candidates"
singularity_image = "linajea/linajea:v1.3-dev"
queue = "gpu_rtx"
data_dir = "../data"
setups_dir = "../unet_setups"
lab = "funke"

[predict]
cell_score_threshold = 0.47
num_workers = 16

[extract_edges]
edge_move_threshold = 30
block_size = [ 7, 501, 501, 501,]
num_workers = 32
use_pv_distance = true

[solve]
track_cost = 1.5
selection_constant = -0.7
weight_node_score = -0.03
weight_edge_score = 0.07
max_cell_move = 30
block_size = [ 5, 501, 501, 501,]
context = [ 2, 99, 99, 99,]
num_workers = 8
from_scratch = false

[evaluate]
gt_db_name = "linajea_160328_gt_side_1"
from_scratch = true
matching_threshold = 15
sparse = true
validation_score = false
window_size = 200
